theme: jekyll-theme-minimal
title: lin
description:
  ğŸ‘‹ Hi there! \n\n
  
  I'm a new grad from University of Connecticut in Computer Science & Engineering whose main interests lie in web/appğŸ“² development and accessibility.
